#!/usr/bin/env python3
"""Collect non-secret security gate and concurrency-eight metrics."""
from __future__ import annotations

import argparse
import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path


def git_head(root: Path) -> str:
    return subprocess.check_output(
        ["git", "-C", str(root), "rev-parse", "HEAD"], text=True
    ).strip()


def load_json(path: Path):
    return json.loads(path.read_text())


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    root = args.root.resolve()
    baseline = [
        row for row in load_json(root / "benchmarks/agent_benchmark.json") if row["concurrency"] == 8
    ]
    optimized = [
        row
        for row in load_json(root / "benchmarks/agent_benchmark_optimized.json")
        if row["concurrency"] == 8
    ]
    optimized_by_operation = {row["operation"]: row for row in optimized}
    profile = next(
        row
        for row in load_json(root / "benchmarks/repository_search_profile.json")
        if row["concurrency"] == 8
    )
    operations = []
    for row in baseline:
        after = optimized_by_operation[row["operation"]]
        operations.append(
            {
                "operation": row["operation"],
                "baseline_p95_ms": row["p95_ns"] / 1_000_000,
                "optimized_p95_ms": after["p95_ns"] / 1_000_000,
                "baseline_p99_ms": row["p99_ns"] / 1_000_000,
                "optimized_p99_ms": after["p99_ns"] / 1_000_000,
                "baseline_throughput_ops_per_sec": row["throughput_ops_per_sec"],
                "optimized_throughput_ops_per_sec": after["throughput_ops_per_sec"],
                "baseline_errors": row["errors"],
                "optimized_errors": after["errors"],
            }
        )
    partition_metrics = load_json(root / "benchmarks/consensus_partition_metrics.json")
    phase14_reads = load_json(root / "benchmarks/phase14_read_benchmark.json")
    phase30_failover = load_json(root / "benchmarks/phase30_multiregion_failover_metrics.json")
    phase31_replay = load_json(root / "benchmarks/phase31_secure_replay_metrics.json")
    phase31_seal_overhead = load_json(root / "benchmarks/phase31_trace_seal_overhead.json")
    phase32_recovery = load_json(root / "benchmarks/phase32_disaster_recovery_metrics.json")
    phase33_recovery = load_json(root / "benchmarks/phase33_durable_recovery_metrics.json")
    phase34_recovery = load_json(root / "benchmarks/phase34_replicated_recovery_metrics.json")
    phase35_recovery = load_json(root / "benchmarks/phase35_multileader_witness_metrics.json")
    phase36_recovery = load_json(root / "benchmarks/phase36_recovery_transport_metrics.json")
    report = {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "commit": git_head(root),
        "gates": {
            "skill_validation": "passed",
            "rust_all_targets": "passed",
            "python_tests": "passed",
            "cli_smoke": "passed",
            "helm_fail_closed": "passed",
            "compose_mtls_smoke": "passed",
            "snapshot_installation": "passed",
            "authenticated_consensus_transport": "passed",
            "signer_rotation_revocation": "passed",
            "durable_external_audit_sink": "passed",
            "phase11_membership_change": "passed",
            "failure_injection_snapshot_recovery": "passed",
            "authenticated_socket_transport": "passed",
            "replay_window_and_cluster_binding": "passed",
            "snapshot_chunk_streaming": "passed",
            "incremental_state_sync": "passed",
            "network_stress_packet_corruption": "passed",
            "authenticated_partition_benchmark": "passed",
            "leader_lease_read_optimization": "passed",
            "linearizable_read_consistency": "passed",
            "election_timer_safety": "passed",
            "failure_detector_boundaries": "passed",
            "replication_flow_control": "passed",
            "replication_backpressure_boundaries": "passed",
            "remote_audit_ordering": "passed",
            "remote_audit_outbox_durability": "passed",
            "log_compaction_safety": "passed",
            "configuration_bound_snapshots": "passed",
            "durable_compaction_manifests": "passed",
            "compaction_recovery": "passed",
            "snapshot_install_readiness": "passed",
            "snapshot_ack_binding": "passed",
            "snapshot_transfer_metrics": "passed",
            "snapshot_bandwidth_backpressure": "passed",
            "snapshot_cancellation": "passed",
            "snapshot_completion_accounting": "passed",
            "durable_term_vote_persistence": "passed",
            "durable_consensus_state_recovery": "passed",
            "epoch_bound_replay_window": "passed",
            "replay_term_floor": "passed",
            "cross_node_compaction_coordination": "passed",
            "compaction_quorum_admission": "passed",
            "follower_triggered_snapshot_requests": "passed",
            "snapshot_request_binding": "passed",
            "socket_layer_backpressure": "passed",
            "per_peer_socket_quotas": "passed",
            "receive_window_admission": "passed",
            "socket_quota_epoch_reset": "passed",
            "durable_transport_queue": "passed",
            "quota_recovery_after_restart": "passed",
            "atomic_queue_cutover": "passed",
            "queue_epoch_binding": "passed",
            "authenticated_durable_delivery": "passed",
            "socket_boundary_crash_injection": "passed",
            "crash_retry_queue_retention": "passed",
            "authenticated_delivery_ack_order": "passed",
            "replicated_ack_quorum": "passed",
            "cross_host_queue_ownership": "passed",
            "authenticated_ack_binding": "passed",
            "failover_owner_lease": "passed",
            "quorum_loss_fences_delivery": "passed",
            "lease_expiry_fences_delivery": "passed",
            "fence_survives_restart": "passed",
            "ownership_transfer_clears_fence": "passed",
            "authenticated_remote_fence_observation": "passed",
            "remote_fence_owner_term_binding": "passed",
            "remote_fence_idempotent": "passed",
            "remote_fence_misbinding_rejected": "passed",
            "region_topology_deterministic": "passed",
            "asymmetric_partition_replayable": "passed",
            "observer_quorum_admission": "passed",
            "split_brain_commit_exclusion": "passed",
            "stale_owner_fenced_after_heal": "passed",
            "transfer_crash_recovers_safely": "passed",
            "clock_skew_boundary_fail_closed": "passed",
            "multi_region_retry_reaches_quorum": "passed",
            "signed_replay_manifest_required": "passed",
            "replay_schedule_hash_bound": "passed",
            "replay_sequence_tick_bounds_enforced": "passed",
            "trusted_key_cluster_epoch_binding": "passed",
            "tampered_schedule_rejected": "passed",
            "trace_seal_verification": "passed",
            "signed_region_failure_observation_required": "passed",
            "distinct_observer_quorum_required": "passed",
            "snapshot_hash_binding_required": "passed",
            "higher_term_epoch_promotion_required": "passed",
            "old_region_fenced_on_commit": "passed",
            "single_active_region_invariant": "passed",
            "idempotent_failover_evidence": "passed",
            "stale_or_conflicting_failover_rejected": "passed",
            "durable_recovery_snapshot_hash_bound": "passed",
            "atomic_recovery_cutover": "passed",
            "partial_staging_cleanup": "passed",
            "restart_preserves_pending_authority": "passed",
            "observer_membership_epoch_bound": "passed",
            "stale_membership_evidence_rejected": "passed",
            "concurrent_partition_race_single_commit": "passed",
            "joint_observer_quorum_required": "passed",
            "joint_to_final_membership_ordering": "passed",
            "replicated_recovery_log_hash_bound": "passed",
            "external_fencing_token_signature_required": "passed",
            "fencing_epoch_monotonicity": "passed",
            "stale_external_fence_rejected": "passed",
            "replicated_authority_restart_continuity": "passed",
            "dynamic_partition_epoch_chaos_safe": "passed",
            "multi_leader_proposal_signature_required": "passed",
            "witness_quorum_arbitration_required": "passed",
            "one_witness_vote_per_round": "passed",
            "conflicting_quorum_split_brain_rejected": "passed",
            "stale_multi_leader_log_rejected": "passed",
            "fencing_token_domain_bound": "passed",
            "fencing_authority_registry_pinned": "passed",
            "fencing_generation_rollback_rejected": "passed",
            "authenticated_transport_envelope_signature_required": "passed",
            "transport_receiver_binding_required": "passed",
            "connection_epoch_replay_window_enforced": "passed",
            "durable_witness_reservation_hash_bound": "passed",
            "reservation_crash_cutover_atomic": "passed",
            "protected_write_exact_fence_required": "passed",
            "cross_host_chaos_duplicate_idempotent": "passed",
            "stale_transport_replay_rejected": "passed",
            "consensus_telemetry_signature_required": "passed",
            "telemetry_producer_registry_bound": "passed",
            "telemetry_epoch_sequence_monotonic": "passed",
            "telemetry_journal_hash_chained": "passed",
            "failover_orchestration_phase_typed": "passed",
            "stale_telemetry_blocks_promotion": "passed",
            "transport_receiver_epoch_churn_safe": "passed",
            "reservation_store_fuzz_no_panic": "passed",
            "fencing_authority_heartbeat_signature_required": "passed",
            "fencing_authority_key_pinned": "passed",
            "fencing_authority_generation_monotonic": "passed",
            "fence_consumer_ack_exact_binding": "passed",
            "supervision_requires_complete_consumer_coverage": "passed",
            "stale_authority_blocks_readiness": "passed",
            "supervision_snapshot_atomic_and_hash_bound": "passed",
            "quarantined_consumer_blocks_readiness": "passed",
            "authority_owner_region_signed": "passed",
            "valid_path_resource_metrics": "passed",
            "persistence_bytes_accounted": "passed",
            "file_fsync_latency_recorded": "passed",
            "directory_fsync_latency_recorded": "passed",
            "staging_recovery_bounded": "passed",
            "resource_budget_fail_closed": "passed",
            "sanitized_durability_evidence": "passed",
            "concurrent_persistence_bounds": "passed",
            "atomic_order_under_concurrency": "passed",
            "unique_staging_target_accounting": "passed",
            "stale_staging_recovery_counted": "passed",
            "concurrent_completion_accounting": "passed",
            "contention_timing_recorded": "passed",
            "active_worker_resource_snapshot": "passed",
            "concurrent_failure_propagation": "passed",
            "cas_writer_signature_required": "passed",
            "replica_ack_signature_required": "passed",
            "cas_expected_generation_hash_exact": "passed",
            "replicated_ack_quorum_required": "passed",
            "replica_ack_conflict_rejected": "passed",
            "nonce_retry_idempotent": "passed",
            "cas_commit_atomic_on_failure": "passed",
            "durable_cas_snapshot_hash_bound": "passed",
            "ownership_claim_signature_required": "passed",
            "atomic_cross_process_lock": "passed",
            "ownership_epoch_fencing": "passed",
            "owner_bound_lease_lifecycle": "passed",
            "stale_staging_cleanup": "passed",
            "managed_recovery_state_fail_closed": "passed",
            "managed_recovery_distinct_quorum": "passed",
            "recovery_evidence_hash_bound": "passed",
            "ownership_bound_cas_permit_required": "passed",
            "cas_request_epoch_exactly_bound": "passed",
            "ownership_record_hash_exactly_bound": "passed",
            "ownership_lock_held_through_quorum": "passed",
            "cas_quorum_failure_preserves_ownership": "passed",
            "successful_cas_advances_ownership_record": "passed",
            "stale_permit_rejected_before_cas": "passed",
            "idempotent_retry_preserves_ownership": "passed",
        },
        "benchmark_concurrency": 8,
        "operations": operations,
        "repository_search_before_after": profile,
        "authenticated_consensus_partition": partition_metrics,
        "phase14_read_optimization": phase14_reads,
        "phase30_multi_region_failover": phase30_failover,
        "phase31_secure_replay": phase31_replay,
        "phase31_trace_seal_overhead": phase31_seal_overhead,
        "phase32_disaster_recovery": phase32_recovery,
        "phase33_durable_recovery": phase33_recovery,
        "phase34_replicated_recovery": phase34_recovery,
        "phase35_multileader_witness": phase35_recovery,
        "phase36_recovery_transport": phase36_recovery,
        "phase37_telemetry_failover": {
            "signed_canonical_events": True,
            "producer_registry_key_pinning": True,
            "epoch_sequence_frontier": True,
            "bounded_labels_and_metrics": True,
            "append_only_hash_chain": True,
            "freshness_gate_blocks_promotion": True,
            "typed_idempotent_orchestration": True,
            "transport_and_reservation_fuzz_panics": 0,
            "trace_storage_bounded": True,
            "secret_material_recorded": False,
            "cluster_mutation_performed": False,
        },
        "phase38_external_fencing_supervision": {
            "signed_authority_heartbeat": True,
            "pinned_authority_and_consumer_keys": True,
            "monotonic_authority_generations": True,
            "exact_consumer_token_binding": True,
            "complete_consumer_coverage_required": True,
            "stale_authority_blocks_readiness": True,
            "atomic_hash_bound_snapshot": True,
            "quarantined_consumer_blocks_readiness": True,
            "secret_material_recorded": False,
            "cluster_mutation_performed": False,
        },
        "phase39_resource_durability": {
            "authority_owner_region_signed": True,
            "valid_path_resource_metrics": True,
            "persistence_bytes_accounted": True,
            "file_fsync_latency_recorded": True,
            "directory_fsync_latency_recorded": True,
            "staging_recovery_bounded": True,
            "resource_budget_fail_closed": True,
            "sanitized_durability_evidence": True,
            "secret_material_recorded": False,
            "cluster_mutation_performed": False,
        },
        "phase40_high_throughput_persistence": {
            "concurrent_persistence_bounds": True,
            "atomic_order_under_concurrency": True,
            "unique_staging_target_accounting": True,
            "stale_staging_recovery_counted": True,
            "concurrent_completion_accounting": True,
            "contention_timing_recorded": True,
            "active_worker_resource_snapshot": True,
            "concurrent_failure_propagation": True,
            "secret_material_recorded": False,
            "cluster_mutation_performed": False,
        },
        "phase41_replicated_durability": {
            "cas_writer_signature_required": True,
            "replica_ack_signature_required": True,
            "cas_expected_generation_hash_exact": True,
            "replicated_ack_quorum_required": True,
            "replica_ack_conflict_rejected": True,
            "nonce_retry_idempotent": True,
            "cas_commit_atomic_on_failure": True,
            "durable_cas_snapshot_hash_bound": True,
            "secret_material_recorded": False,
            "cluster_mutation_performed": False,
        },
        "phase42_cross_process_ownership": {
            "ownership_claim_signature_required": True,
            "atomic_cross_process_lock": True,
            "ownership_epoch_fencing": True,
            "owner_bound_lease_lifecycle": True,
            "stale_staging_cleanup": True,
            "managed_recovery_state_fail_closed": True,
            "managed_recovery_distinct_quorum": True,
            "recovery_evidence_hash_bound": True,
            "secret_material_recorded": False,
            "cluster_mutation_performed": False,
        },
        "phase43_ownership_bound_cas": {
            "ownership_bound_cas_permit_required": True,
            "cas_request_epoch_exactly_bound": True,
            "ownership_record_hash_exactly_bound": True,
            "ownership_lock_held_through_quorum": True,
            "cas_quorum_failure_preserves_ownership": True,
            "successful_cas_advances_ownership_record": True,
            "stale_permit_rejected_before_cas": True,
            "idempotent_retry_preserves_ownership": True,
            "secret_material_recorded": False,
            "cluster_mutation_performed": False,
        },
        "phase15_election_timers": {
            "timer_actions": ["Idle", "StartElection", "SendHeartbeats"],
            "clock_regression": "blocked_until_explicit_reanchor",
            "failure_detector_boundary": "suspect_at_or_after_interval",
            "transport_or_background_threads": False,
        },
        "phase16_replication_flow_control": {
            "actions": ["Idle", "Backpressured", "Send"],
            "one_in_flight_batch_per_peer": True,
            "exact_retry_boundary_is_sendable": True,
            "higher_term_clears_windows": True,
            "clock_uncertainty_blocks_sends": True,
            "transport_or_background_threads": False,
        },
        "phase17_remote_audit": {
            "envelope_signature_binding": True,
            "per_stream_sequence_order": True,
            "idempotent_enqueue": True,
            "gap_and_retry_retention": True,
            "accepted_ack_removes_and_syncs_directory": True,
            "transport_or_sink_quorum": "deployment_boundary",
        },
        "phase18_log_compaction": {
            "bounded_discard_and_retention": True,
            "logical_frontier_translation": True,
            "snapshot_required_for_behind_follower": True,
            "configuration_hash_binding": True,
            "invalid_target_no_mutation": True,
            "persistent_compaction_scheduler": "deployment_boundary",
        },
        "phase19_durable_compaction": {
            "manifest_snapshot_hash_binding": True,
            "fsync_before_atomic_cutover": True,
            "partial_staging_aborts": True,
            "prior_snapshot_preserved": True,
            "recovery_is_idempotent": True,
            "storage_scheduler": "deployment_boundary",
        },
        "phase20_snapshot_install_readiness": {
            "one_active_transfer_per_follower": True,
            "validated_does_not_advance_progress": True,
            "durably_staged_does_not_advance_progress": True,
            "installed_advances_progress": True,
            "exact_retry_boundary": True,
            "ack_hash_and_configuration_binding": True,
            "higher_term_clears_snapshot_state": True,
            "transport_and_storage": "deployment_boundary",
        },
        "phase21_snapshot_transfer_metrics": {
            "per_follower_isolation": True,
            "bytes_sent_and_remaining_are_monotonic": True,
            "rolling_window_is_bounded": True,
            "bandwidth_backpressure_has_exact_retry_tick": True,
            "installed_requires_complete_byte_accounting": True,
            "cancellation_clears_active_transfer": True,
            "cancellation_has_bounded_retry": True,
            "clock_uncertainty_blocks_progress": True,
            "transport_storage_and_scheduler": "deployment_boundary",
        },
        "phase22_durable_term_replay": {
            "term_and_vote_atomic_state_hash": True,
            "staging_recovery_removes_partial_state": True,
            "term_vote_restore_rejects_rollback": True,
            "same_term_vote_exclusivity_survives_restore": True,
            "replay_epoch_is_signature_bound": True,
            "replay_epoch_rotation_clears_windows": True,
            "replay_term_floor_rejects_stale_envelopes": True,
            "bounded_nonce_eviction_is_preserved": True,
            "persistence_and_socket_authority": "deployment_boundary",
        },
        "phase23_compaction_coordination_snapshot_requests": {
            "coordination_plan_is_hash_bound": True,
            "waiting_plan_has_no_mutation": True,
            "remote_quorum_admission_is_explicit": True,
            "stable_and_joint_quorum_logic": True,
            "append_predecessor_requests_snapshot": True,
            "incremental_base_requests_snapshot": True,
            "request_retry_tick_is_hash_bound": True,
            "stale_or_misbinding_requests_fail_closed": True,
            "network_scheduler_and_compaction_authority": "deployment_boundary",
        },
        "phase24_socket_backpressure_quotas": {
            "per_peer_send_isolation": True,
            "exact_frame_byte_admission": True,
            "send_quota_release": True,
            "receive_window_backpressure": True,
            "authentication_precedes_quota_mutation": True,
            "epoch_rotation_clears_quota_state": True,
            "legacy_transport_compatibility": True,
            "socket_threads_and_scheduler": "deployment_boundary",
        },
        "phase25_durable_transport_queues": {
            "queue_frames_are_hash_bound": True,
            "exact_quota_recovery_after_restart": True,
            "atomic_save_and_staging_cleanup": True,
            "fifo_ack_required": True,
            "epoch_mismatch_rejected": True,
            "persistence_failure_rolls_back": True,
            "socket_queue_threads_and_replication": "deployment_boundary",
        },
        "phase26_authenticated_durable_delivery": {
            "authenticated_payload_reverified_before_send": True,
            "one_active_delivery_per_peer": True,
            "ack_only_after_flush": True,
            "crash_points_retaining_queue": 4,
            "restart_retry_after_crash": True,
            "tampered_payload_fails_closed": True,
            "durable_delivery_metrics_non_secret": True,
            "socket_thread_and_process_ownership": "deployment_boundary",
        },
        "phase27_replicated_delivery_ownership": {
            "quorum_ack_required": True,
            "ack_hash_owner_term_epoch_bound": True,
            "idempotent_same_sender_ack": True,
            "conflicting_sender_ack_rejected": True,
            "ownership_transfer_lease_and_term_bound": True,
            "cross_host_restore_validates_source_identity": True,
            "failover_new_owner_can_retry": True,
            "old_owner_cannot_ack_after_transfer": True,
            "transport_and_replica_quorum": "deployment_boundary",
        },
        "phase28_partition_ownership_fencing": {
            "quorum_loss_fences_delivery": True,
            "lease_expiry_fences_delivery": True,
            "fence_survives_restart": True,
            "ownership_transfer_clears_fence": True,
            "network_failure_detector_and_clock_authority": "deployment_boundary",
        },
        "phase29_authenticated_remote_fencing": {
            "authenticated_remote_fence_observation": True,
            "remote_fence_owner_term_binding": True,
            "remote_fence_idempotent": True,
            "remote_fence_misbinding_rejected": True,
            "failure_detector_quorum_authority": "deployment_boundary",
        },
        "phase30_multi_region_failover": {
            "region_topology_is_deterministic": True,
            "asymmetric_partition_is_replayable": True,
            "observer_quorum_admission": True,
            "split_brain_commit_exclusion": True,
            "stale_owner_is_fenced_after_heal": True,
            "transfer_crash_recovers_safely": True,
            "clock_skew_boundary_is_fail_closed": True,
            "multi_region_retry_reaches_quorum": True,
            "transport_and_cloud_region_authority": "deployment_boundary",
        },
        "phase31_secure_replay_verification": {
            "signed_replay_manifest_required": True,
            "replay_schedule_hash_bound": True,
            "replay_sequence_tick_bounds_enforced": True,
            "trusted_key_cluster_epoch_binding": True,
            "tampered_schedule_rejected": True,
            "trace_seal_verification": True,
            "production_key_custody_and_transport": "deployment_boundary",
        },
        "phase32_disaster_recovery_failover": {
            "signed_region_failure_observation_required": True,
            "distinct_observer_quorum_required": True,
            "snapshot_hash_binding_required": True,
            "higher_term_epoch_promotion_required": True,
            "old_region_fenced_on_commit": True,
            "single_active_region_invariant": True,
            "idempotent_failover_evidence": True,
            "stale_or_conflicting_failover_rejected": True,
            "failure_detection_sequence_required": True,
            "conflicting_pending_proposal_rejected": True,
            "terminal_recovery_cycle_protected": True,
            "committed_proposal_identity_bound": True,
            "production_cloud_authority": "deployment_boundary",
        },
        "phase33_durable_recovery": {
            "snapshot_hash_bound": True,
            "atomic_cutover": True,
            "partial_staging_cleanup": True,
            "restart_preserves_pending_authority": True,
            "observer_membership_epoch_bound": True,
            "stale_membership_evidence_rejected": True,
            "concurrent_partition_race_single_commit": True,
            "durable_storage_and_external_fencing": "deployment_boundary",
        },
        "phase34_replicated_recovery": {
            "joint_observer_quorum_required": True,
            "joint_to_final_membership_ordering": True,
            "replicated_recovery_log_hash_bound": True,
            "external_fencing_token_signature_required": True,
            "fencing_epoch_monotonicity": True,
            "stale_external_fence_rejected": True,
            "replicated_authority_restart_continuity": True,
            "dynamic_partition_epoch_chaos_safe": True,
            "transport_process_fencing_and_external_registry": "deployment_boundary",
        },
        "phase35_multileader_witness": {
            "multi_leader_proposal_signature_required": True,
            "witness_quorum_arbitration_required": True,
            "one_witness_vote_per_round": True,
            "conflicting_quorum_split_brain_rejected": True,
            "stale_multi_leader_log_rejected": True,
            "fencing_token_domain_bound": True,
            "fencing_authority_registry_pinned": True,
            "fencing_generation_rollback_rejected": True,
            "transport_failure_detector_and_process_fencing": "deployment_boundary",
        },
        "phase36_recovery_transport": {
            "authenticated_transport_envelope_signature_required": True,
            "transport_receiver_binding_required": True,
            "connection_epoch_replay_window_enforced": True,
            "durable_witness_reservation_hash_bound": True,
            "reservation_crash_cutover_atomic": True,
            "protected_write_exact_fence_required": True,
            "cross_host_chaos_duplicate_idempotent": True,
            "stale_transport_replay_rejected": True,
            "kernel_tls_and_distributed_filesystem": "deployment_boundary",
        },
        "security_notes": {
            "secret_material_recorded": False,
            "cluster_mutation_performed": False,
            "external_sink_mode": "durable file-backed idempotent outbox",
            "snapshot_mode": "atomic durable JSON with hash validation",
            "transport_mode": "Ed25519 envelope identity/term/nonce binding",
            "telemetry_mode": "signed bounded hash-chained journal with freshness gate",
            "fuzz_mode": "deterministic epoch churn with sanitized counters",
            "fencing_supervision_mode": "signed authority heartbeat plus exact consumer acknowledgements",
            "resource_durability_mode": "bounded local fsync, atomic rename, and process-resource instrumentation",
            "high_throughput_persistence_mode": "bounded concurrent unique staging with atomic rename and active-worker resource capture",
            "replicated_durability_mode": "signed replica acknowledgements with quorum-gated single-writer compare-and-swap",
            "cross_process_ownership_mode": "atomic ownership lease epochs with hash-bound managed-volume recovery quorum",
            "ownership_bound_cas_mode": "ownership permit held through replicated CAS quorum and record advancement",
        },
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
    print(json.dumps(report, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
