{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "un1c0.fullname" . }}-admin
  labels:
    {{- include "un1c0.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "un1c0.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: admin
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "un1c0.fullname" . }}-nginx
  labels:
    {{- include "un1c0.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "un1c0.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: nginx
{{- end }}
{{- if .Values.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "un1c0.fullname" . }}-admin
  labels:
    {{- include "un1c0.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "un1c0.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: admin
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "un1c0.name" . }}
              app.kubernetes.io/instance: {{ .Release.Name }}
              app.kubernetes.io/component: nginx
      ports:
        - protocol: TCP
          port: 5000
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 8200
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "un1c0.fullname" . }}-nginx
  labels:
    {{- include "un1c0.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "un1c0.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: nginx
  policyTypes: [Ingress, Egress]
  ingress:
    - ports:
        - protocol: TCP
          port: 8443
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "un1c0.name" . }}
              app.kubernetes.io/instance: {{ .Release.Name }}
              app.kubernetes.io/component: admin
      ports:
        - protocol: TCP
          port: 5000
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
{{- end }}
