{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "un1c0.adminServiceAccountName" . }}
  labels:
    {{- include "un1c0.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "un1c0.nginxServiceAccountName" . }}
  labels:
    {{- include "un1c0.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
